CREATE TABLE `pra01` (
	`num` INT(11) NOT NULL AUTO_INCREMENT,
	`breed` CHAR(30) NULL DEFAULT NULL,
	`name` CHAR(30) NULL DEFAULT NULL,
	`age` INT(11) NULL DEFAULT NULL,
	`phone` CHAR(11) NULL DEFAULT NULL,
	PRIMARY KEY (`num`)
)
COMMENT='내 연습용 테이블~~!!!!'
ENGINE=InnoDB
AUTO_INCREMENT=2
;
